app_main/urls.py
__author__ = 'BUR'
from django.conf.urls import url
from . import views

urlpatterns = [
 #   url(r'^$', views.ret1),
    url(r'^$', views.index, name='index'),
  #  url(r'^(?P<fio_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<fio_id>[0-9]+)/$', views.get_name, name='name1'),
    url(r'^(?P<fio_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<fio_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^images/$', views.sea1),
    url(r'^thanks/$', views.contact),

]

sait1/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = [
  #  url(r'^app_main/', include('app_main.urls', namespace='main1')),
    url(r'^', include('app_main.urls', namespace='main1')),
    url(r'^admin/', include(admin.site.urls)),
]

app_main/models.py
import datetime
from django.db import models
from decimal import Decimal
from sorl.thumbnail import ImageField
from django.forms import ModelForm


class CurrencyField(models.DecimalField, metaclass=models.SubfieldBase):
    def to_python(self, value):
        try:
            return super(CurrencyField, self).to_python(value).quantize(Decimal("0.01"))
        except AttributeError:
            return None

    def __str__(self):
        return self.value


class FIO(models.Model):
    name = models.CharField(u'Имя',max_length=200)
    age = models.IntegerField(u'Вoзраст')
    date_brd = models.DateTimeField(u'Дата рождения')
    phone = models.CharField(u'Телефон',max_length=30, null=True, blank=True)
    mail = models.EmailField(u'Почта',max_length=40)
    desc = models.TextField(u'Описание')
    per1 = models.FloatField(u'Процент')

    def __str__(self):
        return self.name + '  ' + self.desc

class FIOForm(ModelForm):
    class Meta:
        model = FIO
        fields = ['name', 'phone']


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = CurrencyField(max_digits=10, decimal_places=2)
    receive_news = models.BooleanField(default=True, db_index=True)
    slug = models.SlugField(blank=True, null=True)
    updated = models.DateTimeField(auto_now=True, db_index=True)
    votes = models.IntegerField()

    def __str__(self):
        return self.title

    def was_published_today(self):
        return self.pub_date.date() == datetime.date.today()


class Image(models.Model):
    item = models.ForeignKey(Item)
    file = ImageField(upload_to='images')

app_main/forms.py
__author__ = 'BUR'
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label='Your e-mail address')
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message

class FioForm(forms.Form):
    name        = forms.CharField(label='Имя', max_length=100)
    age         = forms.IntegerField(label='Возраст')
    mail        = forms.EmailField(required=False, label='Your e-mail address')
    desc        = forms.CharField(label='Примечание',widget=forms.Textarea)
    phone       = forms.CharField(label='Телефон', max_length=100)
    date_brd    = forms.DateField(label='Дата рождения')

app_main/views.py
from audioop import reverse
from urllib import request
from django.shortcuts import get_object_or_404, render
from django.template import RequestContext, loader
from django.http import HttpResponseRedirect, HttpResponse
# from django.views import generic
# from django.views.generic import TemplateView
from .models import FIO
# --------------------------------------------------
from django.shortcuts import render_to_response
from django.core.mail import send_mail
from app_main.forms   import ContactForm, FioForm
from django.forms.models import modelformset_factory
from django.shortcuts import render_to_response
from app_main.models import FIO ,FIOForm


def get_name(request, fio_id):
    FIOFormSet = modelformset_factory(FIO,form=FIOForm)
  #  FIOFormSet = modelformset_factory(FIO)
    if request.method == 'POST':
        formset = FIOFormSet(request.POST, request.FILES)
        if formset.is_valid():
            formset.save()
            # do something.
    else:
        formset = FIOFormSet()
    return render(request, 'app_main/fio_set.html', {
        "formset": formset,
    })

def get_name1(request, fio_id):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = FioForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = FioForm()

    return render(request, 'app_main/fio.html', {'form': form})

def ret1(request):
    return HttpResponse('Пришли RET1')

# --------------------------------------------------
def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                ['siteowner@example.com'],
            )
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = ContactForm(
            initial={'subject': 'I love your site!','email': 'uxx@mail.ru'}
        )
    return render(request,'app_main/contact_form.html', {'form': form})


def test1(request):
    return render(request,'app_main/contact_form.html')

def sea1(request):
    error = False
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            error = True
        else:
            fio1 = FIO.objects.filter(name__icontains=q)
            return render_to_response('app_main/search_results.html',
                                      {'fio1': fio1, 'query': q})

    return render_to_response('app_main/search_form.html',  {'errors': error})



# --------------------------------------------------

def index(request):
    fio_list = FIO.objects.all()
    context = {'fio_list': fio_list}
    return render(request, 'app_main/lst_fio.html', context)


def detail(request, fio_id):
    question = get_object_or_404(FIO, pk=fio_id)
    return render(request, 'app_main/detail.html', {'question': question})


def results(request, fio_id):
    return HttpResponse("Привет, Мир. Это polls index.")
    #   question = get_object_or_404(FIO, pk=fio_id)
    #   return render(request, 'app_main/results.html', {'question': question})


def vote(request, fio_id):
    p = get_object_or_404(FIO, pk=fio_id)
    try:
        selected_choice = p.age
    except (KeyError, FIO.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'app_main/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('main1:results', args=(p.id,)))

app_main/templates/app_main/contact_form.html
<html>
<head>
    <title>Контакт</title>
    <style type="text/css">
    ul.errorlist {
        margin: 0;
        padding: 0;
    }
    .errorlist li {
        background-color: red;
        color: white;
        display: block;
        font-size: 10px;
        margin: 0 0 3px;
        padding: 4px 5px;
    }
</style>
</head>
<body>
    <h1>Контакт</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>

    {% endif %}

    <form action="" method="post">
        {% csrf_token %}
        <div class="field">
            {{ form.subject.errors }}
            <label for="id_subject">Subject:</label>
            {{ form.subject }}
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Your e-mail address:</label>
            {{ form.email }}
        </div>

        <div class="field{% if form.message.errors %} errors{% endif %}">
    {% if form.message.errors %}
        <ul>
        {% for error in form.message.errors %}
            <li><strong>{{ error }}</strong></li>
        {% endfor %}
        </ul>
    {% endif %}
    <label for="id_message">Message:</label>
    {{ form.message }}
</div>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

app_main/templates/app_main/detail.html
<h1>{{ question.name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'main1:vote' question.id %}" method="post">
    <label for="choice{{ forloop.counter }}">{{ question.age }}</label><br />
<input type="submit" value="Vote" />
</form>

app_main/templates/app_main/fio.html
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

app_main/templates/app_main/fio_set.html
<form action="" method="post">
    {% csrf_token %}
    {{formset.as_p }}
    <input type="submit" value="Submit" />
</form>

app_main/templates/app_main/idex1.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
  app_main ind1
</body>
</html>

app_main/templates/app_main/lst_fio.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'app_main/style.css' %}" />

<h1 align="center">  Список ФИО   </h1>
{% if fio_list %}
    <ul>
    {% for p in fio_list %}
        <li><a href="{% url 'main1:index'%}{{ p.id }}">{{ p.name}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

app_main/templates/app_main/results.html
<<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.pk %}">Vote again?</a>

app_main/templates/app_main/search_form.html
<html>
<head>
    <title>Поиск</title>
</head>
<body>
    {% if error %}
        <p style="color: red;">Введите данные.</p>
    {% endif %}
    <form action="/images/" method="get">
        <input type="text" name="q" title="Заголовок">
        <input type="submit" value="Поиск">
    </form>
</body>
</html>

app_main/templates/app_main/search_results.html
<p>Поиск: <strong>{{ query }}</strong></p>

{% if fio1 %}
    <p>Найдено {{ fio1|length }} ФИО </p>
    <ul>
        {% for book in fio1 %}
        <li>{{ book.name }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>Пусто.</p>
{% endif %}

app_main/templates/app_main/vote.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
  vote
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
   sait1 Привет...
</body>
</html>